app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__,  template_folder="templates")

from app.main import routes

app/main/routes.py
from app.main import main
from flask import render_template, request


@main.route('/assignment')
def show_assignment():
    return render_template("assignment.html")

@main.route('/add_event',methods=['GET', 'POST'])
def add_event():

    message = ""
    if request.method == 'POST':
        # Process form data
        name = request.form.get('name')
        date = request.form.get('date')
        time = request.form.get('time')
        description = request.form.get('description')
        message = f"A new {name}, was added on  {date} at {time}."

    return render_template('add_event.html', message=message)


@main.route('/delete_event')
def delete_event():
    return render_template("delete_event.html")


@main.route('/')
def show_events():
    list_of_events = [
        {
            "name": "cina cu Elena",
            "date": "2025-01-21",
            "time": "11:50",
            "description": "in Bucuresti, la restaurant Vatra"
        },
    {
        "name": "pranz cu Andrei",
        "date": "2025-01-25",
        "time": "13:30",
        "description": "la restaurant Casa Verona"
    },
    {
        "name": "intalnire de afaceri",
        "date": "2025-01-30",
        "time": "10:00",
        "description": "in Bucuresti, biroul principal"
    }
    ]

    return render_template("main_view.html",  events=list_of_events)

app/main/templates/add_event.html
{% extends "base.html" %}

{% block title %}Add Event{% endblock %}


{% block header %}
            <h1>Add Event</h1>
{% endblock %}


{% block sidebar %}
    <ul>
        <li>
            <a href="{{ url_for('main.show_events') }}">
                <strong>Home Page</strong>
            </a>
        </li>
    </ul>
{% endblock %}



{% block content %}
    <h1>Please add your event</h1>

    <form method="POST">
        <label for="name"><strong>Name:</strong></label><br>
        <input type="text" id="name" name="name" required><br><br>

        <label for="date"><strong>Date:</strong></label><br>
        <input type="date" id="date" name="date" required><br><br>

        <label for="time"><strong>Time:</strong></label><br>
        <input type="time" id="time" name="time" required><br><br>

        <label for="description"><strong>Description:</strong></label><br>
        <input type="description" id="description" name="description" ><br><br>

        <button type="submit">Submit</button>
    </form>

{% endblock %}

{% block footer %}
            <p> <a  href="{{ url_for('main.show_assignment') }}"><strong>IT School! </strong> </a></p>
{% endblock %}

app/main/templates/assignment.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}


{% block header %}
            <h1>Your first Event Planner</h1>
{% endblock %}


{% block sidebar %}
    <ul>
        <li>
            <a href="{{ url_for('main.show_events') }}"><br>
                <strong>Home</strong>
            </a>
        </li>


    </ul>
{% endblock %}



{% block content %}
    <picture>
  <source media="(min-width: 250px)" srcset="static/EventPlanner.png">
  <img src="{{ url_for('static', filename='EventPlanner.png') }}"
       alt="Event Planner"
       style="max-width: 100%; height: auto; display: block; margin: auto;">
</picture>
{% endblock %}

app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default Title{% endblock %}</title>

    <style>
        * {
    box-sizing: border-box;
}

html, body {
    height: 100%; /* Ensures full height */
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column; /* Stacks header, section, footer */
}

body {
    font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
    background-color: #D8C8BB;

    text-align: center;
    font-size: 35px;
    color: black;
}

/* Make section take up remaining space */
section {
    display: flex;
    align-items: stretch; /* Ensures both sections grow equally */
    flex: 1; /* Makes section fill available space */
}

nav {
    width: 15%;
    background: #f8aa69;
    padding: 20px;
    font-size: 25px;
}

nav ul {
    list-style-type: none;
    padding: 0;
}

article {
    width: 90%;
    background-color: #f1f1f1;
    padding: 20px;
}

picture img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: auto;
}

/* Style the footer - stays at bottom */
footer {
    background-color: #D8C8BB;

    text-align: center;
    color: black;
    font-size: 15px;
}

<!--This is needed so that the footer and content in extended pages are not shown as links -->

    </style>
</head>
<body>

    <header>
        {% block header %}
            <h1>Default Header</h1>
        {% endblock %}
    </header>

    <section>
        <nav>
            {% block sidebar %}
                <ul>

                </ul>
            {% endblock %}
        </nav>

        <article>
            {% block content %}
                <h1>Default Content</h1>
            {% endblock %}
        </article>
    </section>

    <footer>
        {% block footer %}
            <p><strong>IT School<strong></p>
        {% endblock %}
    </footer>

</body>
</html>

app/main/templates/delete_event.html
{% extends "base.html" %}

{% block title %}Delete Event{% endblock %}


{% block header %}
            <h1>Delete Event</h1>
{% endblock %}


{% block sidebar %}
    <ul>
        <li>
            <a href="{{ url_for('main.show_events') }}">
                <strong>Home</strong>
            </a>
        </li>
    </ul>
{% endblock %}



{% block content %}
    <h1>Here add content for the Delete Event</h1>
{% endblock %}

{% block footer %}
            <p><strong> <a href="{{ url_for('main.show_assignment') }}">IT School<strong></p>
{% endblock %}

app/main/templates/main_view.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}


{% block header %}
            <h1>Events View</h1>
{% endblock %}


{% block sidebar %}
    <ul>

        <li>
            <a href="{{ url_for('main.add_event') }}"><br>
                <strong>Add Event</strong>
            </a>
        </li>

        <li>
            <a href="{{ url_for('main.delete_event') }}"><br>
                <strong>Delete Event</strong>
            </a>
        </li>


    </ul>
{% endblock %}



{% block content %}
    {% for event in events %}
<!--rethink page using bootstraps-->
    <ul>
        <li><strong>Name:</strong> {{ event.name }}</li>
        <li><strong>Date:</strong> {{ event.date }}</li>
        <li><strong>Time:</strong> {{ event.time }}</li>
        <li><strong>Description:</strong> {{ event.description }}</li>
    </ul>
    {% endfor %}

{% endblock %}

{% block footer %}
            <p><strong> <a href="{{ url_for('main.show_assignment') }}">IT School<strong></p>
{% endblock %}